### ISSUE TITLE
Abstrair a finalização

### ISSUE THREAD

**Issue by claudiosmweb** [greguly/cielo-woocommerce#16]
Agora como temos várias formas de checkout precisamos abstrair o checkout no método:

```php
public function process_payment( $order_id )
```

Agora esse método esta tentando tratar tudo de uma vez, precisamos dividir isso em métodos menores para manter organizado e simplificar a manutenção.

**Comment by gopaulo** [comment]
Claudio - estou pensando em fazer algo assim 

```
	public function process_payment( $order_id ) {

		$payment_function = 'process_payment_'.$this->store_contract;
		return call_user_func($payment_function,$order_id);
	}
```

e aí ter uma função para cada solução process_payment_webservice, process_payment_buypage_cielo e no futuro process_payment_checkout_cielo

mas todas protected.

**Comment by gopaulo** [comment]
@claudiosmweb  - Teria como você dar uma check na abstração que eu fiz.

**Comment by claudiosmweb** [comment]
Pode trocar por outros métodos e dentro de process_payment apenas usar if, não precisa de muita coisa.
De qualquer forma, final de semana vou tirar para terminar os detalhes, assim qualquer coisa dou uma arrumada.

**Comment by claudiosmweb** [comment]
Resolvido em 8a0642cad21491d989120011af6b42861d25afb7
