### ISSUE TITLE
Parcelamento por SKU

### ISSUE THREAD

**Issue by Guilherme011** [greguly/cielo-woocommerce#2]
Galera, bom dia...

meu cliente me pediu isso e nao acho uma forma de fazer... existe algum meio de determinar o parcelamento por produto?

exemplo:  existe um produto especifico que NAO pode ser parcelado...

tks,

**Comment by claudiosmweb** [comment]
Não é possível, podemos verificar a possibilidade de adicionar isso na versão 4.0.0 do plugin.

Estamos aceitando doações para desenvolvimento dessa nova versão: http://www10.vakinha.com.br/VaquinhaE.aspx?e=342130

**Comment by claudiosmweb** [comment]
Adicionei o filtro `wc_cielo_max_installments`, assim você pode trabalhar com o `WC()->cart` para ver quais produtos tem no carrinho e assim mudar a quantidade máxima de parcelas.
