### ISSUE TITLE
Adicionar script para controlar pagamento em debito e parcelamento com webservice

### ISSUE THREAD

**Issue by claudiosmweb** [greguly/cielo-woocommerce#29]
Temos que controlar a exibição do valor de debido para visa e master, além de controlar o valor dar parcelas como fazemos com os outros gateways.
Isso pode ser feito baseado no checkout payment que retorna a bandeira do cartão e agora tem suporte para aura e elo.

**Comment by gopaulo** [comment]
Não entendi esse issue. Atualmente ele exibe um dropdown com esses valores.

**Comment by gopaulo** [comment]
E se apresentassemos esses valores em <radio> group ao invés de select (dropdown) ?

**Comment by claudiosmweb** [comment]
É que agora aparece debido para todas os métodos de pagamento, até para os que não tem.
