### ISSUE TITLE
Adicionar alertas sobre SSL e versão do WooCommerce para webservice

### ISSUE THREAD

**Issue by claudiosmweb** [greguly/cielo-woocommerce#31]
O webservice vai funcionar apenas para WooCommerce 2.3.x ou superior, além de precisar de SSL instalado no servidor.

**Comment by gopaulo** [comment]
A gente vai fazer algum check se o site ta rodando em ssl (is_ssl()) ou vamos dar só o aviso ? 
Esse aviso é similar ao que você fez para a vaquinha dentro do html-admin-page.php ?

**Comment by gopaulo** [comment]
Vou fazer o check de versão de woocommerce via admin_notices()

```
	if('webservice'==$this->store_contract && !$this->woocommerce_version_check()){ 
 				add_action( 'admin_notices', array( $this, 'version_not_supported_message_for_webservice' ) );
			}
```
