### ISSUE TITLE
Email enviado pela Cielo: Atualização da tabela de Bins Elo

### ISSUE THREAD

**Issue by greguly** [greguly/cielo-woocommerce#32]
<html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>Template Cielo</title></head><body bgcolor="#ffffff" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0"><table width="600" border="0" cellpadding="0" cellspacing="0" align="center"><tr><td><table width="600" border="0" cellpadding="0" cellspacing="0"><tr><td><img border="0" style="display:block;" src="http://cielodigital.com.br/templatepadrao/template-email_01.jpg" width="600" height="20" alt="" /></td></tr></table><table width="600" border="0" cellpadding="0" cellspacing="0"><tr><td><h2 style="margin:0; padding:0 55px 0 26px; font-family:Arial, Helvetica, sans-serif; font-weight:bold; color:#000; line-height:30px; text-transform:uppercase;">Informação Importante Bins da bandeira Elo</h2></td><td><img border="0" style="display:block;" src="http://cielodigital.com.br/templatepadrao/template-email_03_semslogan.jpg" width="159" height="160" alt="" /></td><td width="26" height="160"></td></tr></table><table width="600" border="0" cellpadding="0" cellspacing="0"><tr><td width="600" height="22"></td></tr><tr><td><p style="margin:0 0 22px; padding: 0 26px; font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:19px; color:#000; font-weight:normal;">Caro cliente,</p><p style="margin:0 0 22px; padding: 0 26px; font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:19px; color:#000; font-weight:normal;">A bandeira Elo disponibilizou novos bins de cartões de crédito e débito para os bancos. Pelo monitoramento constante que fazemos nas nossas plataformas, identificamos que algumas vendas com esses cartões não estão sendo aceitas.
</p><p style="margin:0 0 22px; padding: 0 26px; font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:19px; color:#000; font-weight:normal;">Para não perder vendas, confira a relação de bins e range criados para o cadastramento manual ou de atualização do seu sistema.<br /><br />509048, 509067, 509049,	509069, 509050, 509074, 509068, 509040, 509045, 509051, 509046, 509066, 509047, 509042,
509052, 509043, 509064 e 509040
<br /><br /><strong>Fique atento</strong>: Estes bins começam com o número 5. Por favor, verifique se há alguma restrição dessa característica na sua plataforma para a bandeira Elo.<br /><br />Caso seja necessário consultar a lista oficial dos Bins na ABA (American Bankers Association), acesse o site <a href="http://t.umail.com.br/t.aspx?p=8360931&c=NjQ2MTM2&e=cielo@omniwp.com.br&l=OTIx&up=6918446&u=aHR0cDovL3d3dy5hYmEuY29t" target="_blank">www.aba.com</a>.</p><p style="margin:0 0 22px; padding: 0 26px; font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:19px; color:#000; font-weight:normal;">Atenciosamente,<br /><br />Cielo S/A</p></td></tr><tr><td width="600" height="18"></td></tr></table><table width="600" border="0" cellpadding="0" cellspacing="0"><tr><td valign="top">&nbsp;</td><td colspan="3" rowspan="2" valign="top">&nbsp;</td></tr><tr><p style="margin:0; padding:0 26px;">No caso de dúvidas, entre em contato:<br />4002-9111 (Capitais e Regiões Metropolitanas)<br />0800-570-0111 (Demais Localidades)<br />www.cielo.com.br</p><p /></tr></table></td></tr></table></body></html>

**Comment by claudiosmweb** [comment]
Estamos validando isso com JS e esta tudo ok para versão 4.0 :)
