### ISSUE TITLE
Apresentar cálculo dos juros para parcelamentos

### ISSUE THREAD

**Issue by gopaulo** [greguly/cielo-woocommerce#34]
Uma outra sugestão talvez seria para acrescentar quais são os juros que estão sendo aplicados nas parcelas.

referencia: https://wordpress.org/support/topic/informar-cartao-de-credito?replies=2#post-6494823

**Comment by claudiosmweb** [comment]
![tooltip_001](https://cloud.githubusercontent.com/assets/1264099/6795673/04f1bba0-d1c3-11e4-8a46-2b8aa4cbb128.png)
Estava olhando e talvez podemos fazer igual o submarino e americanas fazem.

**Comment by gopaulo** [comment]
Cláudio,
   postei alguns comentários em cima do issue #7  - que tem a a ver com esse issue também..  O cálculo do juros parece que estava errado. não calculava ou aumentava mes a mes - isso só apareceu na hora que eu coloquei o texto para aparecer que nem você sugeriu. 

Exemplo
Cálculo Antigo
Juros de 2%
Parcela = valor_total * (100 + JUROS/100)   
Obs: só que o valor do juros independia do número de parcelas (era 3% simples) ; mas o cálculo de parcelamento usado pelas lojas é cálculo de juros composto - ou seja o valor final aumenta a medida que o número de parcelas aumenta (a.m.) 

Cálculo Novo
CF (coeficiente de financiamento) - http://www.matematicadidatica.com.br/CalculoPrestacao.aspx <http://www.matematicadidatica.com.br/CalculoPrestacao.aspx>
Com isso o juros mensal (a.m) é composto e agregado sobre o valor do mes anterior - ou seja minha parcela para 4 vezes com juros irá somar um valor final maior do que o que a minha parcela em 3 vezes com juros. 



Dúvida: Vamos adicionar o texto/cálculo de CET (Custo efetivo total)

**Comment by claudiosmweb** [comment]
Parece que esta tudo ok aqui agora.

**Comment by CaTeIM** [comment]
Olá, sei que foi habilitado a opção de mostrar os juros no parcelamento, mas onde eu acho o código para desabilitar? Estou olhando aqui, mas infelizmente não tive habilidade para isso! Por hora, agradeço.
