### ISSUE TITLE
Dividir o gateway em dois, um para debito e outro para crédito

### ISSUE THREAD

**Issue by claudiosmweb** [greguly/cielo-woocommerce#35]
Dividir vai ser um pouco complicado, mas vamos ganhar em outras coisas.
Primeiro que não será mais necessário de javascript para remover o método de cartão de debito para os métodos que não são Visa e Master, além disso fica melhor para o cliente, já que vai ficar claro o que ele esta fazendo, se quer pagar com cartão de crédito ele pode ir direto ou pagar com debito também.

![screenshot from 2015-03-25 00 27 53](https://cloud.githubusercontent.com/assets/1264099/6817889/cec80e4e-d285-11e4-81db-e066d65841bf.png)

Mais ou menos como Submarino, PagSeguro, Americanas e todo mundo faz.

Em especial agora com o webservice fica bem estranho o que esta rolando, já que o cliente deve preencher o cartão e apenas depois selecionar as parcelas, se ele colocar um cartão de crédito visa por exemplo, vai mostra a opção de debito, até podemos detectar que o cartão dele é de credito e ocultar a opção de debito, mas no final javascript é ruim para isso, porque pode ter algum erro de javascript no checkout e tornar mais confuso ainda para o cliente, já que ele vai chegar para pagar com cartão de crédito e por padrão ou não ter a opção de debito.

**Comment by gopaulo** [comment]
A idéia seria adicionar isso debaixo da opção CIELO  - um passo a mais (e.g. a pessoa seleciona cielo e depois seleciona débito ) ou separar isso e mostrar as opções (CIELO DEBITO E CIELO CRÉDITO) ?

**Comment by claudiosmweb** [comment]
Virar dois gateways msmo, um Cielo Crédito e outro Cielo Debito.

**Comment by gopaulo** [comment]
A gente vai implementar isso já para o 3.2 ?

**Comment by claudiosmweb** [comment]
Vai ser melhor para funcionar o webservice agora

**Comment by gopaulo** [comment]
Posso manter as 2 classes dos 2 gateways dentro do mesmo arquivo ? ou vc prefere separar toda a estrutura de diretórios ?

**Comment by claudiosmweb** [comment]
Vamos separar assim vai estruturar melhor.

**Comment by gopaulo** [comment]
Cláudio,
   eu abstrai a classe WC_Cielo_Gateway e criei 2 classes herdadas que carregassem apenas os dados e características que fosse aplicados a cada contexto (crédito ou débito). Com isso eu aproveitei toda a programação e interface já programada sem precisar ter redundância. 

Eu comitei o início da divisão de gateways - pelo menos o backend e a parte de load no checkout estão ok para o BuyPage; precisa testar para o webservice e verificar onde o processo de pagamento vai ser afetado  com essas mudanças (carregamento das chaves de afiliacao - vide abaixo) 

Algumas observações - quando a gente dá o split no gateway o único dado que ficou reduntante foi a chave de afiliação e da loja da cielo - não sei muito bem como fazer - pq "teoricamente" ele poderia ter uma chave pra débito e outra chave pra crédito ... como que a gente poderia fazer com isso ? ou deixa assim ?

**Comment by claudiosmweb** [comment]
Ficou bom, mas acho que podemos até fazer sem herança, porque assim diminuimos alguns ifs, maior duplicação vai ser apenas nas opções, mas isso é tranquilo.

**Comment by claudiosmweb** [comment]
Ou manter herança e abstrair melhor isso.

**Comment by claudiosmweb** [comment]
É isso não ajudou muito, da forma que você dividiu sumiu várias coisas de JS que eram importantes.
Estou precisando refazer várias coisas e dividir realmente para funcionar melhor.
Unica coisa que estou duplicado agora vai as opções.

**Comment by gopaulo** [comment]
OK - Eu tentei fazer com herança e aproveitar o máximo possível de ambos. Alguns do js estavam funcionando justamente para alterar os valores baseado se fosse debito ou credito (com a divisão eles ficaram desnecessários) - por isso que removi

Com relação ao admin - eu apenas codifiquei uns selectors mais genéricos que funcionaria para ambas as telas e criei os métodos com as opções detalhadas de cada parte (debito ou credito) 

Pensei em reaproveitar ao máximo o código que já existia antes e só redefinr o que fosse estritamente necessário ;

**Comment by claudiosmweb** [comment]
Falo de coisas como isso aqui no default:

```js
if ( 'discover' === card ) {
    $( 'option', installments ).not( '.cielo-at-sight' ).remove();
}
```

discover não recebe parcelas, só pagamento a vista.

Estou escrevendo de novo algumas coisas e melhorando isso para dividir, ter JS para cada um.

**Comment by claudiosmweb** [comment]
Do admin estava tudo perfeito, mas no frontend tinha coisas assim, estou agora dando uma melhorada nisso.

**Comment by claudiosmweb** [comment]
Agora rodando mais tranquilo.
Falta o de debit e então vai estar tudo pronto :)

**Comment by gopaulo** [comment]
Me desculpe se deu mais dor de cabeça . Vamos aprendendo e melhorando 😊 



—

**Comment by claudiosmweb** [comment]
Não precisa pedir desculpas, tudo de boa.
Eu juntei a classe de helper com o do gateway agora.
Separei algumas coisas e criando métodos para validar debito e crédito.

**Comment by claudiosmweb** [comment]
Agora foi.
