### ISSUE TITLE
Icones para maestro e visa electron

### ISSUE THREAD

**Issue by claudiosmweb** [greguly/cielo-woocommerce#36]
Agora que dividimos os gateways seria bom ter icones para maestro e visa electron.
Falei com o cara que me ajudou da ultima vez, talvez já arrumamos isso.

**Comment by claudiosmweb** [comment]
O Anilton vai me mandar hoje dia 30.
Assim já faço o CSS para isso.

**Comment by gopaulo** [comment]
não seria válido talvez a gente fazer isso via svg (os ícons já estão disponíveis online)

**Comment by claudiosmweb** [comment]
Não sei agora, até porque só usamos esses icones para a opção do BuyPage Cielo que vamos remover no futuro.
Recebi os icones, vou adicionar logo.

**Comment by monecchi** [comment]
@claudiosmweb Valeu pelo plugin, nas configurações Eu uso a Solução Webservice (formulário). Quando comecei a usar o plugin percebi que era simples aproveitar as classes que o plugin adicionava no input do número do cartão pra poder mostrar as bandeiras dos cartões aceitos.

No meu projeto localhost já deixei o form do jeito que eu quero, ficou bem bacana, como mostra a imagem abaixo, depois apliquei a customização num site de testes que usa o tema Storefront, dá pra ver um demo aqui:


Quem quiser explorar essa customização pode checar esse gist: https://gist.github.com/monecchi/042b0db481f93f30b13e495272945d84

Você vai precisar das seguintes imagens:
