### ISSUE TITLE
Problemas com Bandeiras na finalização do pedido

### ISSUE THREAD

**Issue by brunobedin** [greguly/cielo-woocommerce#42]
Bom dia estou homologando o site junto a Cielo e tive esse email como resolver isso?

Informamos que ao acessarmos a Finalização do Pedido e selecionarmos pagamento com cartão de crédito, não são exibidas as bandeiras que serão homologadas e nem mesmo exibidas ao inserirmos o número do cartão na página de pagamento. Lembramos que é ideal que o portador do cartão seja informado e ou alertado da bandeira que está de utilizando para realizar o pagamento. 
Após verificar as informações, favor replicar email para realizarmos novos testes.

**Comment by claudiosmweb** [comment]
Ao inserir o número do cartão aparece a bandeira, isso é padrão do WooCommerce, se não aparece é alguma notificação do seu tema.
Você também pode usar o filtro `wc_cielo_credit_icon`.

Por exemplo:

```php
function custom_wc_cielo_credit_icon( $icon ) {
    return 'link-com-as-bandeiras.png';
}

add_filter( 'wc_cielo_credit_icon', 'custom_wc_cielo_credit_icon' );
```

**Comment by brunobedin** [comment]
adiciona isso no functions.php?

**Comment by claudiosmweb** [comment]
Sim, pode ser no functions.php

**Comment by brunobedin** [comment]
eu coloquei lá nao deu muito certo, eu nao sei exatamente aonde no functions eu coloco, mais eu coloquei e nao mudou nada.

**Comment by claudiosmweb** [comment]
Você alterou `link-com-as-bandeiras.png` pelo link do seus icones?
