### ISSUE TITLE
Parcela minima por produto

### ISSUE THREAD

**Issue by filipecompleta** [greguly/cielo-woocommerce#43]
Gostaria de saber se teria como determinar a parcela minima por produto pois em uma loja que estou desenvolvendo tenho produtos que podem ser vendidos em 12 vezes e tenho produtos que só podem ser vendidos em 6 vezes, pensei em algo no valor da parcela minima pois caso o produto não tenha esta definição o sistema de pagamento utilizasse as configurações do sistema de pagamento Cielo woocommerce por padrão.
Isso seria possível?
Teria uma dificuldade muito grande para implementar ?
Caso seja possivel como posso fazer esta configuração ou implementação?

**Comment by claudiosmweb** [comment]
Não tem como fazer isso por produto.
Entretanto sinta-se livre para enviar Pull Request com novos filtros para você fazer isso.

**Comment by filipecompleta** [comment]
Obrigado pela resposta vou ver o que fazer e como fazer isso.
