### ISSUE TITLE
Erro Pagamento

### ISSUE THREAD

**Issue by rafasegat** [greguly/cielo-woocommerce#44]
Olá,

Houve um erro no pagamento num site do meu cliente e abaixo segue o log. Não consegui identificar nenhuma mensagem de erro. Se alguem puder ajudar.. É o pedido #1725

<pre>
04-22-2015 @ 03:45:13 - Requesting a transaction for order 237 with the follow data: WC_Cielo_XML Object
(
    [@attributes] => Array
        (
            [id] => 237-1429674313
            [versao] => 1.3.0
        )

    [dados-pedido] => WC_Cielo_XML Object
        (
            [numero] => 237
            [valor] => 126601
            [moeda] => 986
            [data-hora] => 2015-04-22T03:45:11
            [idioma] => PT
        )

    [forma-pagamento] => WC_Cielo_XML Object
        (
            [bandeira] => mastercard
            [produto] => 2
            [parcelas] => 9
        )

    [url-retorno] => http%3A%2F%2Fmegalandia.com.br%2F2015%2Fwc-api%2FWC_Cielo_Credit_Gateway%2F%3Fkey%3Dwc_order_5537194924a62%26amp%3Border%3D237
    [autorizar] => 3
    [capturar] => true
    [gerar-token] => false
)

04-22-2015 @ 03:45:14 - Transaction successfully created for the order 237
05-13-2015 @ 00:08:11 - Requesting a transaction for order 570 with the follow data: WC_Cielo_XML Object
(
    [@attributes] => Array
        (
            [id] => 570-1431475691
            [versao] => 1.3.0
        )

    [dados-pedido] => WC_Cielo_XML Object
        (
            [numero] => 570
            [valor] => 253203
            [moeda] => 986
            [data-hora] => 2015-05-13T00:08:11
            [idioma] => PT
        )

    [forma-pagamento] => WC_Cielo_XML Object
        (
            [bandeira] => elo
            [produto] => 2
            [parcelas] => 11
        )

    [url-retorno] => http%3A%2F%2Fmegalandia.com.br%2F2015%2Fwc-api%2FWC_Cielo_Credit_Gateway%2F%3Fkey%3Dwc_order_555295eb93666%26amp%3Border%3D570
    [autorizar] => 2
    [capturar] => true
    [gerar-token] => false
)

05-13-2015 @ 00:08:11 - Transaction successfully created for the order 570
05-29-2015 @ 06:02:30 - Requesting a transaction for order 1023 with the follow data: WC_Cielo_XML Object
(
    [@attributes] => Array
        (
            [id] => 1023-1432879348
            [versao] => 1.3.0
        )

    [dados-pedido] => WC_Cielo_XML Object
        (
            [numero] => 1023
            [valor] => 200
            [moeda] => 986
            [data-hora] => 2015-05-29T06:02:26
            [idioma] => PT
        )

    [forma-pagamento] => WC_Cielo_XML Object
        (
            [bandeira] => diners
            [produto] => 1
            [parcelas] => 1
        )

    [url-retorno] => https%3A%2F%2Fmegalandia.com.br%2Fwc-api%2FWC_Cielo_Credit_Gateway%2F%3Fkey%3Dwc_order_556800f2c2aad%26amp%3Border%3D1023
    [autorizar] => 2
    [capturar] => true
    [gerar-token] => false
)

05-29-2015 @ 06:02:30 - Transaction successfully created for the order 1023
05-29-2015 @ 06:03:03 - Requesting a transaction for order 1023 with the follow data: WC_Cielo_XML Object
(
    [@attributes] => Array
        (
            [id] => 1023-1432879383
            [versao] => 1.3.0
        )

    [dados-pedido] => WC_Cielo_XML Object
        (
            [numero] => 1023
            [valor] => 200
            [moeda] => 986
            [data-hora] => 2015-05-29T06:02:26
            [idioma] => PT
        )

    [forma-pagamento] => WC_Cielo_XML Object
        (
            [bandeira] => visa
            [produto] => 1
            [parcelas] => 1
        )

    [url-retorno] => https%3A%2F%2Fmegalandia.com.br%2Fwc-api%2FWC_Cielo_Credit_Gateway%2F%3Fkey%3Dwc_order_556800f2c2aad%26amp%3Border%3D1023
    [autorizar] => 3
    [capturar] => true
    [gerar-token] => false
)

05-29-2015 @ 06:03:04 - Transaction successfully created for the order 1023
05-29-2015 @ 06:03:05 - Checking the transaction status for order 1023...
05-29-2015 @ 06:03:05 - Recovered the order 1023 data successfully
05-29-2015 @ 06:03:05 - Cielo payment status: 5
05-29-2015 @ 06:04:13 - Requesting a transaction for order 1024 with the follow data: WC_Cielo_XML Object
(
    [@attributes] => Array
        (
            [id] => 1024-1432879453
            [versao] => 1.3.0
        )

    [dados-pedido] => WC_Cielo_XML Object
        (
            [numero] => 1024
            [valor] => 100
            [moeda] => 986
            [data-hora] => 2015-05-29T06:04:12
            [idioma] => PT
        )

    [forma-pagamento] => WC_Cielo_XML Object
        (
            [bandeira] => amex
            [produto] => 1
            [parcelas] => 1
        )

    [url-retorno] => https%3A%2F%2Fmegalandia.com.br%2Fwc-api%2FWC_Cielo_Credit_Gateway%2F%3Fkey%3Dwc_order_5568015ced093%26amp%3Border%3D1024
    [autorizar] => 2
    [capturar] => true
    [gerar-token] => false
)

05-29-2015 @ 06:04:13 - Transaction successfully created for the order 1024
05-29-2015 @ 06:05:34 - Requesting a transaction for order 1024 with the follow data: WC_Cielo_XML Object
(
    [@attributes] => Array
        (
            [id] => 1024-1432879534
            [versao] => 1.3.0
        )

    [dados-pedido] => WC_Cielo_XML Object
        (
            [numero] => 1024
            [valor] => 100
            [moeda] => 986
            [data-hora] => 2015-05-29T06:04:12
            [idioma] => PT
        )

    [forma-pagamento] => WC_Cielo_XML Object
        (
            [bandeira] => mastercard
            [produto] => 1
            [parcelas] => 1
        )

    [url-retorno] => https%3A%2F%2Fmegalandia.com.br%2Fwc-api%2FWC_Cielo_Credit_Gateway%2F%3Fkey%3Dwc_order_5568015ced093%26amp%3Border%3D1024
    [autorizar] => 3
    [capturar] => true
    [gerar-token] => false
)

05-29-2015 @ 06:05:34 - Transaction successfully created for the order 1024
05-29-2015 @ 06:05:44 - Requesting a transaction for order 1024 with the follow data: WC_Cielo_XML Object
(
    [@attributes] => Array
        (
            [id] => 1024-1432879544
            [versao] => 1.3.0
        )

    [dados-pedido] => WC_Cielo_XML Object
        (
            [numero] => 1024
            [valor] => 100
            [moeda] => 986
            [data-hora] => 2015-05-29T06:04:12
            [idioma] => PT
        )

    [forma-pagamento] => WC_Cielo_XML Object
        (
            [bandeira] => mastercard
            [produto] => 1
            [parcelas] => 1
        )

    [url-retorno] => https%3A%2F%2Fmegalandia.com.br%2Fwc-api%2FWC_Cielo_Credit_Gateway%2F%3Fkey%3Dwc_order_5568015ced093%26amp%3Border%3D1024
    [autorizar] => 3
    [capturar] => true
    [gerar-token] => false
)

05-29-2015 @ 06:05:44 - Transaction successfully created for the order 1024
06-17-2015 @ 13:48:09 - Requesting a transaction for order 1563 with the follow data: WC_Cielo_XML Object
(
    [@attributes] => Array
        (
            [id] => 1563-1434548889
            [versao] => 1.3.0
        )

    [dados-pedido] => WC_Cielo_XML Object
        (
            [numero] => 1563
            [valor] => 3060
            [moeda] => 986
            [data-hora] => 2015-06-17T13:48:09
            [idioma] => PT
        )

    [forma-pagamento] => WC_Cielo_XML Object
        (
            [bandeira] => mastercard
            [produto] => 1
            [parcelas] => 1
        )

    [url-retorno] => https%3A%2F%2Fmegalandia.com.br%2Fwc-api%2FWC_Cielo_Credit_Gateway%2F%3Fkey%3Dwc_order_55817a992f915%26amp%3Border%3D1563
    [autorizar] => 3
    [capturar] => true
    [gerar-token] => false
)

06-17-2015 @ 13:48:10 - Transaction successfully created for the order 1563
06-17-2015 @ 13:48:40 - Requesting a transaction for order 1563 with the follow data: WC_Cielo_XML Object
(
    [@attributes] => Array
        (
            [id] => 1563-1434548920
            [versao] => 1.3.0
        )

    [dados-pedido] => WC_Cielo_XML Object
        (
            [numero] => 1563
            [valor] => 3060
            [moeda] => 986
            [data-hora] => 2015-06-17T13:48:09
            [idioma] => PT
        )

    [forma-pagamento] => WC_Cielo_XML Object
        (
            [bandeira] => mastercard
            [produto] => 1
            [parcelas] => 1
        )

    [url-retorno] => https%3A%2F%2Fmegalandia.com.br%2Fwc-api%2FWC_Cielo_Credit_Gateway%2F%3Fkey%3Dwc_order_55817a992f915%26amp%3Border%3D1563
    [autorizar] => 3
    [capturar] => true
    [gerar-token] => false
)

06-17-2015 @ 13:48:40 - Transaction successfully created for the order 1563
06-17-2015 @ 13:52:10 - Requesting a transaction for order 1563 with the follow data: WC_Cielo_XML Object
(
    [@attributes] => Array
        (
            [id] => 1563-1434549130
            [versao] => 1.3.0
        )

    [dados-pedido] => WC_Cielo_XML Object
        (
            [numero] => 1563
            [valor] => 3060
            [moeda] => 986
            [data-hora] => 2015-06-17T13:48:09
            [idioma] => PT
        )

    [forma-pagamento] => WC_Cielo_XML Object
        (
            [bandeira] => mastercard
            [produto] => 2
            [parcelas] => 3
        )

    [url-retorno] => https%3A%2F%2Fmegalandia.com.br%2Fwc-api%2FWC_Cielo_Credit_Gateway%2F%3Fkey%3Dwc_order_55817a992f915%26amp%3Border%3D1563
    [autorizar] => 3
    [capturar] => true
    [gerar-token] => false
)

06-17-2015 @ 13:52:11 - Transaction successfully created for the order 1563
06-17-2015 @ 13:52:12 - Checking the transaction status for order 1563...
06-17-2015 @ 13:52:12 - Recovered the order 1563 data successfully
06-17-2015 @ 13:52:12 - Cielo payment status: 6
06-17-2015 @ 16:42:44 - Requesting a transaction for order 1564 with the follow data: WC_Cielo_XML Object
(
    [@attributes] => Array
        (
            [id] => 1564-1434559364
            [versao] => 1.3.0
        )

    [dados-pedido] => WC_Cielo_XML Object
        (
            [numero] => 1564
            [valor] => 3070
            [moeda] => 986
            [data-hora] => 2015-06-17T16:41:57
            [idioma] => PT
        )

    [forma-pagamento] => WC_Cielo_XML Object
        (
            [bandeira] => visa
            [produto] => 1
            [parcelas] => 1
        )

    [url-retorno] => https%3A%2F%2Fmegalandia.com.br%2Fwc-api%2FWC_Cielo_Credit_Gateway%2F%3Fkey%3Dwc_order_5581a3551581f%26amp%3Border%3D1564
    [autorizar] => 3
    [capturar] => true
    [gerar-token] => false
)

06-17-2015 @ 16:42:46 - Transaction successfully created for the order 1564
06-17-2015 @ 16:42:48 - Checking the transaction status for order 1564...
06-17-2015 @ 16:42:48 - Recovered the order 1564 data successfully
06-17-2015 @ 16:42:48 - Cielo payment status: 5
07-27-2015 @ 18:51:52 - Requesting a transaction for order 1703 with the follow data: WC_Cielo_XML Object
(
    [@attributes] => Array
        (
            [id] => 1703-1438023112
            [versao] => 1.3.0
        )

    [dados-pedido] => WC_Cielo_XML Object
        (
            [numero] => 1703
            [valor] => 2480
            [moeda] => 986
            [data-hora] => 2015-07-27T18:51:52
            [idioma] => PT
        )

    [forma-pagamento] => WC_Cielo_XML Object
        (
            [bandeira] => mastercard
            [produto] => 1
            [parcelas] => 1
        )

    [url-retorno] => https%3A%2F%2Fmegalandia.com.br%2Fwc-api%2FWC_Cielo_Credit_Gateway%2F%3Fkey%3Dwc_order_55b67dc86fac6%26amp%3Border%3D1703
    [autorizar] => 3
    [capturar] => true
    [gerar-token] => false
)

07-27-2015 @ 18:51:53 - Transaction successfully created for the order 1703
07-27-2015 @ 18:52:18 - Requesting a transaction for order 1703 with the follow data: WC_Cielo_XML Object
(
    [@attributes] => Array
        (
            [id] => 1703-1438023138
            [versao] => 1.3.0
        )

    [dados-pedido] => WC_Cielo_XML Object
        (
            [numero] => 1703
            [valor] => 2480
            [moeda] => 986
            [data-hora] => 2015-07-27T18:51:52
            [idioma] => PT
        )

    [forma-pagamento] => WC_Cielo_XML Object
        (
            [bandeira] => mastercard
            [produto] => 1
            [parcelas] => 1
        )

    [url-retorno] => https%3A%2F%2Fmegalandia.com.br%2Fwc-api%2FWC_Cielo_Credit_Gateway%2F%3Fkey%3Dwc_order_55b67dc86fac6%26amp%3Border%3D1703
    [autorizar] => 3
    [capturar] => true
    [gerar-token] => false
)

07-27-2015 @ 18:52:19 - Transaction successfully created for the order 1703
07-27-2015 @ 18:53:25 - Requesting a transaction for order 1703 with the follow data: WC_Cielo_XML Object
(
    [@attributes] => Array
        (
            [id] => 1703-1438023205
            [versao] => 1.3.0
        )

    [dados-pedido] => WC_Cielo_XML Object
        (
            [numero] => 1703
            [valor] => 2480
            [moeda] => 986
            [data-hora] => 2015-07-27T18:51:52
            [idioma] => PT
        )

    [forma-pagamento] => WC_Cielo_XML Object
        (
            [bandeira] => mastercard
            [produto] => 1
            [parcelas] => 1
        )

    [url-retorno] => https%3A%2F%2Fmegalandia.com.br%2Fwc-api%2FWC_Cielo_Credit_Gateway%2F%3Fkey%3Dwc_order_55b67dc86fac6%26amp%3Border%3D1703
    [autorizar] => 3
    [capturar] => true
    [gerar-token] => false
)

07-27-2015 @ 18:53:26 - Transaction successfully created for the order 1703
07-27-2015 @ 18:53:46 - Requesting a transaction for order 1703 with the follow data: WC_Cielo_XML Object
(
    [@attributes] => Array
        (
            [id] => 1703-1438023226
            [versao] => 1.3.0
        )

    [dados-pedido] => WC_Cielo_XML Object
        (
            [numero] => 1703
            [valor] => 2480
            [moeda] => 986
            [data-hora] => 2015-07-27T18:51:52
            [idioma] => PT
        )

    [forma-pagamento] => WC_Cielo_XML Object
        (
            [bandeira] => mastercard
            [produto] => 2
            [parcelas] => 2
        )

    [url-retorno] => https%3A%2F%2Fmegalandia.com.br%2Fwc-api%2FWC_Cielo_Credit_Gateway%2F%3Fkey%3Dwc_order_55b67dc86fac6%26amp%3Border%3D1703
    [autorizar] => 3
    [capturar] => true
    [gerar-token] => false
)

07-27-2015 @ 18:53:47 - Transaction successfully created for the order 1703
07-27-2015 @ 18:53:48 - Checking the transaction status for order 1703...
07-27-2015 @ 18:53:49 - Recovered the order 1703 data successfully
07-27-2015 @ 18:53:49 - Cielo payment status: 6
08-03-2015 @ 13:34:10 - Requesting a transaction for order 1706 with the follow data: WC_Cielo_XML Object
(
    [@attributes] => Array
        (
            [id] => 1706-1438608850
            [versao] => 1.3.0
        )

    [dados-pedido] => WC_Cielo_XML Object
        (
            [numero] => 1706
            [valor] => 4190
            [moeda] => 986
            [data-hora] => 2015-08-03T13:34:10
            [idioma] => PT
        )

    [forma-pagamento] => WC_Cielo_XML Object
        (
            [bandeira] => mastercard
            [produto] => 2
            [parcelas] => 2
        )

    [url-retorno] => https%3A%2F%2Fmegalandia.com.br%2Fwc-api%2FWC_Cielo_Credit_Gateway%2F%3Fkey%3Dwc_order_55bf6dd22320f%26amp%3Border%3D1706
    [autorizar] => 3
    [capturar] => true
    [gerar-token] => false
)

08-03-2015 @ 13:34:13 - Transaction successfully created for the order 1706
08-03-2015 @ 13:34:14 - Checking the transaction status for order 1706...
08-03-2015 @ 13:34:14 - Recovered the order 1706 data successfully
08-03-2015 @ 13:34:14 - Cielo payment status: 6
08-26-2015 @ 18:38:36 - Requesting a transaction for order 1721 with the follow data: WC_Cielo_XML Object
(
    [@attributes] => Array
        (
            [id] => 1721-1440614316
            [versao] => 1.3.0
        )

    [dados-pedido] => WC_Cielo_XML Object
        (
            [numero] => 1721
            [valor] => 7790
            [moeda] => 986
            [data-hora] => 2015-08-26T18:38:35
            [idioma] => PT
        )

    [forma-pagamento] => WC_Cielo_XML Object
        (
            [bandeira] => mastercard
            [produto] => 2
            [parcelas] => 5
        )

    [url-retorno] => https%3A%2F%2Fmegalandia.com.br%2Fwc-api%2FWC_Cielo_Credit_Gateway%2F%3Fkey%3Dwc_order_55de07ac0359f%26amp%3Border%3D1721
    [autorizar] => 3
    [capturar] => true
    [gerar-token] => false
)

08-26-2015 @ 18:38:37 - Transaction successfully created for the order 1721
08-26-2015 @ 18:38:38 - Checking the transaction status for order 1721...
08-26-2015 @ 18:38:38 - Recovered the order 1721 data successfully
08-26-2015 @ 18:38:38 - Cielo payment status: 6
09-21-2015 @ 14:53:08 - Requesting a transaction for order 1725 with the follow data: WC_Cielo_XML Object
(
    [@attributes] => Array
        (
            [id] => 1725-1442847188
            [versao] => 1.3.0
        )

    [dados-pedido] => WC_Cielo_XML Object
        (
            [numero] => 1725
            [valor] => 64232
            [moeda] => 986
            [data-hora] => 2015-09-21T14:53:08
            [idioma] => PT
        )

    [forma-pagamento] => WC_Cielo_XML Object
        (
            [bandeira] => visa
            [produto] => 2
            [parcelas] => 3
        )

    [url-retorno] => https%3A%2F%2Fmegalandia.com.br%2Fwc-api%2FWC_Cielo_Credit_Gateway%2F%3Fkey%3Dwc_order_560019d411e22%26amp%3Border%3D1725
    [autorizar] => 3
    [capturar] => true
    [gerar-token] => false
)

09-21-2015 @ 14:53:09 - Transaction successfully created for the order 1725
09-21-2015 @ 14:53:10 - Checking the transaction status for order 1725...
09-21-2015 @ 14:53:10 - Recovered the order 1725 data successfully
09-21-2015 @ 14:53:10 - Cielo payment status: 5
09-21-2015 @ 14:54:08 - Requesting a transaction for order 1725 with the follow data: WC_Cielo_XML Object
(
    [@attributes] => Array
        (
            [id] => 1725-1442847248
            [versao] => 1.3.0
        )

    [dados-pedido] => WC_Cielo_XML Object
        (
            [numero] => 1725
            [valor] => 64232
            [moeda] => 986
            [data-hora] => 2015-09-21T14:53:08
            [idioma] => PT
        )

    [forma-pagamento] => WC_Cielo_XML Object
        (
            [bandeira] => mastercard
            [produto] => 2
            [parcelas] => 3
        )

    [url-retorno] => https%3A%2F%2Fmegalandia.com.br%2Fwc-api%2FWC_Cielo_Credit_Gateway%2F%3Fkey%3Dwc_order_560019d411e22%26amp%3Border%3D1725
    [autorizar] => 3
    [capturar] => true
    [gerar-token] => false
)

09-21-2015 @ 14:54:10 - Transaction successfully created for the order 1725
09-21-2015 @ 14:54:11 - Checking the transaction status for order 1725...
09-21-2015 @ 14:54:12 - Recovered the order 1725 data successfully
09-21-2015 @ 14:54:12 - Cielo payment status: 5

</pre>

**Comment by claudiosmweb** [comment]
Não tem nenhum erro ai.

Se você for capaz de explicar isso daqui:

> Houve um erro no pagamento num site do meu cliente e abaixo segue o log

Talvez eu consiga te ajudar com algo.
Mas até então pelo log o plugin funciona completamente bem.

**Comment by rafasegat** [comment]
Mas o pagamento não foi efetuado.. gostaria de saber da causa...

**Comment by claudiosmweb** [comment]
@rafasegat precisa de um pai de santo então, porque você não esta me dando detalhes de ABSOLUTAMENTE nada e também no log esta tudo ok.

O que aparece como `Cielo payment status: 5` significa que a transação não foi autorizada.
Quem autoriza ou não é a Cielo e não este plugin!
Se for essa sua dúvida, você esta perguntando no lugar errado!

**Comment by rafasegat** [comment]
Beleza, já entrei em contato com a Cielo e resolvi.

Obrigado

**Comment by claudiosmweb** [comment]
Alias, se for ambiente de testes, eu espero que você não tenha sido vacilão e pulado esta parte da documentação do plugin:

![screenshot from 2015-10-05 14 36 12](https://cloud.githubusercontent.com/assets/1264099/10288310/73610916-6b6e-11e5-8466-9b182f9f1acf.png)

**Comment by rafasegat** [comment]
Não está em ambiente de testes, já está em produção. Inclusive já foi validado pela Cielo.

Está funcionando perfeitamente o plugin, aquele pagamento não efetuado foi por causa de limite do cartão estourado ou transação suspeita.
