### ISSUE TITLE
Log de erro no cielo-woocommerce

### ISSUE THREAD

**Issue by hostyand** [greguly/cielo-woocommerce#45]
Boa noite Pessoal,

Sou iniciante nesta area, e estou com uma dificuldade no checkout no cielo woocommerce, aparece a a famosa mensagem "Um erro aconteceu ao processar o seu pagamento, por favor, tente novamente ou entre em contato para conseguir assistência."

Não entendo o log por isso envio o mesmo para que alguém possa me ajudar, já tentei de tudo que meu conhecimento permite mas sem sucesso.

10-08-2015 @ 01:29:42 - An error occurred while requesting the transaction: WP_Error Object
(
    [errors] => Array
        (
            [http_request_failed] => Array
                (
                    [0] => SSL certificate problem, verify that the CA cert is OK. Details:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
                )

        )

obrigado!

**Comment by claudiosmweb** [comment]
Isso é problema no seu servidor que é incapaz de verificar o SSL da Cielo.
Provavelmente esta usando OpenSSL desatualizado. Converse com suporte do seu servidor sobre isso.

**Comment by hostyand** [comment]
Ok Claudio muito obrigado, mas você diz o meu servidor de hospedagem ou do SSL, eu contratei da Godaddy, SSL padrão de 256.

Obrigado!

**Comment by claudiosmweb** [comment]
Leia de novo:

> Isso é problema no seu servidor que é incapaz de verificar o SSL da Cielo.

SEU SERVIDOR QUE É INCAPAZ DE VERIFICAR O SSL DA CIELO.

SEU SERVIDOR!

Não é nada com o SSL que você comprou na GoDaddy, É O SEU SERVIDOR!

**Comment by hostyand** [comment]
Obrigado Claudio por sua resposta!

Entrei em contato com meu servidor que é a Locaweb, e fui informado que o Openssl esta atualizado e sem problemas,

Me deram também esta informação:

Neste caso conforme instruções da própria Cielo com relação a atualização no protocolo do Certificado deixando de utilizar o protocolo SSLv3 como forma de Criptografia e aceitando somente o protocolo TLS. 

È necessario alterar a linha "curl_setopt($sessao_curl, CURLOPT_SSLVERSION, 3); " para "curl_setopt($sessao_curl, CURLOPT_SSLVERSION, 4); " do arquivo "/pedidos/includes/include.php".

Porém realmente não conseguir encontrar este caminho, 

Você pode me ajudar por favor?

Mais uma vez obrigado!

**Comment by greguly** [comment]
Conforme o Claudio já disse o problema é no teu servidor :-(

Eles te falaram besteira, mencionando arquivos que não existem.

Ali em cima da página tem um formulário de busca, procura por CURLOPT_SSLVERSION e vais descobrir que este plugin já utiliza CURLOPT_SSLVERSION 4

https://github.com/greguly/cielo-woocommerce/search?utf8=%E2%9C%93&q=CURLOPT_SSLVERSION

Então a solução é procurar um servidor que funcione.

**Comment by claudiosmweb** [comment]
@hostyand isso que você fez é totalmente inseguro.
Versão do SSL da Cielo é a 4.
Seu servidor que não é capaz de verificar isso e não verificar SSL é inseguro também e não é CPI Compliance!

Se estivesse atualizado, isso não aconteceria, mas é Locaweb, você espera mesmo ter um e-commerce usando Locaweb?

**Comment by hostyand** [comment]
@claudiosmweb  e @greguly  Muito obrigado pelas respostas, eu acredito mesmo que o plugin utiliza o CURLOPT_SSLVERSION 4.

Vocês podem me indicar um servidor de hospedagem bom e que eu não tenha este tipo de problema?

Obrigado!

**Comment by claudiosmweb** [comment]
O plugin não utiliza nada, o plugin É OBRIGADO a verificar por SSL na versão 4.
Qualquer servidor VPS, assim você tem controle no que esta instalado na maquina.
Se esta usando plano compartilhado na Locaweb você nunca vai conseguir ter um e-commerce.

**Comment by paulortoledo** [comment]
Conseguiu resolver @hostyand
