### ISSUE TITLE
Facilitar a integração com antifraudes.

### ISSUE THREAD

**Issue by mestr3** [greguly/cielo-woocommerce#46]
Acredito que para facilitar a integração com soluções antifraude(FControl, ClearSale) seria necessário implementar algum filtro em que poderia utilizar os dados do pedido para fazer um POST ou GET para o sistema do antifraude. Adicionalmente deveriamos ter a opção de não capturar automaticamente a transação pela cielo.

Atualmente minha necessidade é usar esse modelo de integração.
https://secure.fcontrol.com.br/Manager/ManuaisFControl/integracao/Frame/frame.aspx

Porém acredito que num segundo momento implementar os filtros que falhassem o pedido caso o antifraude acuse fraude seria uma otima ideia, mas neste caso só funcionaria para o modelo do antifraude que utilize SOAP.

**Comment by mestr3** [comment]
Um adendo (Não sei se é possível):
Uma metabox para realizar a captura dentro do admin seria genial.

**Comment by claudiosmweb** [comment]
Só me dizer o que precisa de filtros a mais para facilitar isso.
Já temos alguns que podem ser utilizados, além de algumas actions também.

>  Uma metabox para realizar a captura dentro do admin seria genial.

Já esta nos planos isso.

**Comment by claudiosmweb** [comment]
Fechando por falta de feedback.

**Comment by mestr3** [comment]
Boa tarde @claudiosanches  e @carlosbezz,
contribuindo aqui para as pessoas que necessitem disso no futuro.
Como fiz diversas customizações no plugin para meu uso, segue abaixo um resumo do que é necessário na questão do antifraude:

O ideal é que exista um action (ou filter, eu nunca sei bem quando é um ou outro) dentro da função "process_webservice_payment", após o recebimento do retorno da cielo, pois precisaremos do NSU, que conseguimos através no '$response->autorizacao->nsu' e do IP (WC_Geolocation::get_ip_address()) para usar com o iframe do FCONTROL. Ou de forma simples, basta salvar o IP e o NSU em uma "post_meta" associada a $order->id.

A metabox com o iframe é bem simples na verdade, fiz associada ao pedido, utilizando essas informações adicionais que falei. Porém o ideal, seria melhorar a funcionalidade da metabox adicionando um botão para a captura manual da venda, depois de checado o status no antifraude.

@carlosbezz, é uma ideia geral do que deve ser feito. Como não desenvolvi pensando em compartilhar, muito do que fiz está entremeado às regras de negócio do cliente.  Quem sabe podemos desenvolver um solução mais generalista aqui de forma colaborativa, o Cláudio tem muita experiência nisso e é um grande colaborador.

Abraços!
