### ISSUE TITLE
Erro "SSL connection timeout"

### ISSUE THREAD

**Issue by heitorsilva** [greguly/cielo-woocommerce#48]
Olá pessoal!

Eu verifiquei vários tópicos do Fórum de suporte do plugin, e em todos o @claudiosmweb diz que o erro "SSL connection timeout" é algum problema no servidor que o Woocommerce está rodando.

Eu gostaria de uma ajuda para identificar onde está esse problema, e vou relatar o que já fiz e como é a infra do servidor do meu cliente:

- Meu cliente tem um plano de hospedagem na Dreamhost
- O plano de hospedagem dele inclui um certificado SSL de 2048bits da Comodo
- Temos acesso por SSH no servidor (sem sudo e sem root), e o ambiente dele é bem isolado, tendo como configurar o php.ini separadamente dos outros clientes da Dreamhost
- O PHP que está rodando é o 5.6.10
- O comando curl -v https://ecommerce.cielo.com.br/servicos/ecommwsec.do funcionou e deu o retorno:  

    * About to connect() to ecommerce.cielo.com.br port 443 (#0)
    * Trying 200.172.63.8... connected
    * successfully set certificate verify locations:
    * CAfile: none  
      CApath: /etc/ssl/certs
    * SSLv3, TLS handshake, Client hello (1):

- Wordpress está na versão 4.4
- Woocommerce está na versão 2.4.12
- Vocês podem ver o phpinfo() do servidor aqui: https://www.abolha.com/testphp2.php

Toda vez que tentamos rodar um pagamento por débito ou crédito, recebemos o erro:

```php
12-22-2015 @ 17:58:25 - An error occurred while requesting the transaction: WP_Error Object
(
    [errors] => Array
        (
            [http_request_failed] => Array
                (
                    [0] => SSL connection timeout
                )

        )

    [error_data] => Array
        (
        )

)
```

A única coisa que tentei até agora, foi sobrescrever no php.ini as diretivas openssl.cafile e openssl.capath com caminhos que criei na mão, com o arquivo da parte pública do certificado SSL do meu cliente... Não deu certo.

Vi no manual da CIELO que tem um script shell para rodar no servidor e instalar 3 certificados. Ainda não fiz isso...

Esse "SSL Connection Timeout" pode ser a falta desses 3 certificados instalados na pasta /etc/ssl/certs? Preciso de uma orientação para o que mais olhar para botar o plugin de vocês para rodar...

Agradeço desde já e aguardo um retorno...

**Comment by claudiosmweb** [comment]
Atualiza OpenSSL do seu servidor.

**Comment by heitorsilva** [comment]
O OpenSSL do servidor que estou usando é o OpenSSL 1.0.1 14 Mar 2012. Ele não é o suficiente? A versão stable (LTS) atual é a 1.0.2... a diferença parece pequena. Preciso mesmo atualizá-lo?

**Comment by heitorsilva** [comment]
Só para contribuir com qualquer pessoa que passar pelo mesmo problema, a solução para o meu caso foi:

Migrar da hospedagem da Dreamhost para um servidor que eu tivesse controle total (fomos para Dreamcompute da própria Dreamhost). Tendo acesso como root, pude instalar a versão 1.0.1k do OpenSSL, e pude instalar 3 certificados da CIELO, através de um script shell que está no manual deles do webservice versão 1.5.

Com ambos instalados, o checkout do Woocommerce começou a funcionar sem problemas e o webservice gerou os resultados que ficaram gravados nos logs.
