### ISSUE TITLE
Salvar um campo com o valor total do pedido com o juros do cartão

### ISSUE THREAD

**Issue by claudiosmweb** [greguly/cielo-woocommerce#50]
Ref: https://wordpress.org/support/topic/acertar-o-valor-total-do-pedido-para-o-cliente-e-para-o-administrador-erro-no?replies=1#post-8159795

**Comment by claudiosmweb** [comment]
Fechado em favor de #49

**Comment by ruipossodelli** [comment]
Obrigado, Cláudio! Fico feliz em ter ajudado. Aguardo novidades!

**Comment by Carlos-Bezerra** [comment]
Claudio, bom dia.
Estamos passando pelo mesmo problema, gostaria de saber em que pé anda esse problema, se teve uma solução ou não.
Desde já agradeço e parabéns pelo trabalho.
