### ISSUE TITLE
Arredondamento do valor das parcelas quando não é cobrado juros

### ISSUE THREAD

**Issue by davidWebmaster** [greguly/cielo-woocommerce#51]
Bom dia a todos,

No wecommerce que estou desenvolvendo, me deparei com esse problema. Quando não existe juros aplicáveis ao parcelamento o plugin continua arredondando o valor das parcelas quando não há uma divisão exata, isso tem feito com que os valores do site não batam com os do SAP do meu cliente. A pergunta é: Existe algum tipo de configuração que me permita deixar uma das parcelas com o resto da divisão? Dessa forma teria o valor total batendo com o valor do produto no SAP.

**Comment by claudiosanches** [comment]
Não tem, se quiser enviar um Pull Request ajudando com a forma que os valores são arredondados eu gradeço.
