### ISSUE TITLE
Campos para cartão

### ISSUE THREAD

**Issue by rafa-acioly** [greguly/cielo-woocommerce#52]
Na ultima atualização do woocommerce/wordpress o plugin deixou de exibir os campos do cartões quando selecionado credito/debito, fazendo com que o usuário precise submeter o formulário para gerar o erro de campos vazios para aí sim aparecer os campos.

**Comment by claudiosmweb** [comment]
Não é o plugin que exibe os cartões, por padrão quem exibe é o WooCommerce. Se não esta acontecendo isso, é porque tem algo errado no seu tema.

**Comment by rafa-acioly** [comment]
não me referi aos cartões sendo exibidos como opções Claudio, me referi aos campos para digitar os dados do cartão...

**Comment by claudiosmweb** [comment]
@rafa-acioly pior ainda, então é erro de JavaScript na sua página, por isso que não abre os campos.
