### ISSUE TITLE
Limite de caracteres está errado no campo número do cartão

### ISSUE THREAD

**Issue by rics** [greguly/cielo-woocommerce#53]
Alguns cartões possuem 19 dígitos em seu número, mas no form de finalização de compra o limite para digitação é de apenas 16 dígitos (que é o mais comum mesmo). Fui conferir na documentação da CIELO e eles já permitem que o campo receba os 19 dígitos, então deve ser só questão de alterar a parte da interface mesmo. Acho...

**Comment by claudiosmweb** [comment]
O campo no form aceita 22: https://github.com/greguly/cielo-woocommerce/blob/master/templates/credit-card/webservice-payment-form.php#L17

**Comment by rics** [comment]
Pode crer, eu vi isso também. Será que pode ser a máscara do campo que está limitando a entrada do dados? Porque tem uma máscara divindo os números em 4 grupos de 4 dígitos, mas não manjo muito de javascript e não consegui encontrar nada xeretando os códigos aqui no repositório.

**Comment by claudiosmweb** [comment]
Pode ser a mascara, mas quem aceita 19 numeros é cartão Aura e tem habilitado para ele aceitar isso.

**Comment by rics** [comment]
Então, o cartão em questão é da bandeira Mastercard, débito da Caixa Econômica. Bizarro, né? Nunca tinha visto antes também.

**Comment by claudiosmweb** [comment]
Não existe Mastercard débito, na real é Maestro.

**Comment by claudiosmweb** [comment]
Na verdade o problema é no WooCommerce e não neste plugin.
https://github.com/woothemes/woocommerce/issues/11012

**Comment by rics** [comment]
Isso é só uma questão de marcas eu acho, porque no cartão tá lá Mastercard Débito, como logo e tudo. No site lá da Cielo, na parte de bandeiras, eles também estão falando em Mastercard Débito e não mais em Maestro. Talvez eles estejam mudando isso, não sei mesmo o porque de ser assim e não Maestro. Vai saber o que esses caras estão aprontando.

**Comment by rics** [comment]
Opa, beleza! Vou acompanhar por lá. Se precisar realizar algum teste ou algo assim, algo que eu possa ajudar, estou à postos cara.

**Comment by arymaynart** [comment]
Olá. O erro permanece. Não aceita cartão de Débito com mais de 16 dígitos. Já aconteceu com um cartão da caixa de 19 dígitos e uma do Itaú de 23 dígitos. Usando Woocommerce 3.2.5.
