### ISSUE TITLE
Produtos com condições diferenciadas de pagamento

### ISSUE THREAD

**Issue by HumbertoCPereira** [greguly/cielo-woocommerce#55]
Boa tarde!
Gostaria de tirar uma dúvida: estou montando uma loja virtual cujos produtos terão condições diferenciadas de parcelamento. Por exemplo, o PRODUTO A só poderá ser pago em 1x e o PRODUTO B em 10x. Hoje, a página de pagamentos está somando os valores dos dois produtos e dividindo por 10, quando o correto seria considerar, na 1a parcela, o valor integral do PRODUTO A + 1/10 do PRODUTO B. Seria possível fazer esta configuração para que os valores sejam enviados corretamente para a Cielo?

Obrigado!

**Comment by greguly** [comment]
Olá,

O plugin não permite este tipo de configuração, você precisa de um desenvolvedor para criar um código que faça isto.

Abraços,
Gabriel

**Comment by HumbertoCPereira** [comment]
Obrigado pela rápida resposta. Alguém para indicar?

Sds.

Em quinta-feira, 18 de agosto de 2016, Gabriel Reguly <
notifications@github.com> escreveu:
