### ISSUE TITLE
Parcelamento com juros.

### ISSUE THREAD

**Issue by daniloarodrigues** [greguly/cielo-woocommerce#56]
Estou tentando colocar juros no webservice da cielo, porém o cálculo não está sendo realizado. Ele sempre repassa o valor sem os juros. Alguém sabe dizer se tem algo errado?

**Comment by claudiosmweb** [comment]
Tem configurações para isso, basta configurar o que quer no plugin.

**Comment by daniloarodrigues** [comment]
O prolema é justamente esse. Eu coloco o valor, coloco para cobrar juros a partir de uma determinada parcela, mas quando vou finalizar a compra, todas as parcelas estão sem juros.

**Comment by claudiosmweb** [comment]
Esta configurando errado então.
Estava testando isso no último final de semana e funciona ok.
