### ISSUE TITLE
Melhorar texto mostrando as parcelas do cartão no site e emails

### ISSUE THREAD

**Issue by claudiosmweb** [greguly/cielo-woocommerce#7]
https://wordpress.org/support/topic/informar-cartao-de-credito?replies=2
https://wordpress.org/support/topic/nao-fica-claro-a-quantidade-de-parcela-escolhida-nos-emails-dos-clientes?replies=2

**Comment by gopaulo** [comment]
Alguma sugestão de como melhorar esse texto ? 

Opção 1:
2x de R$100,00 (com juros de R$3,00 por parcela)

Opção 2:
2x de R$100,00 (com 5% de juros) 

Opção 3:
2x de R$97,00 + R$3,00 de juros

**Comment by claudiosmweb** [comment]
Acredito que essa segunda é melhor, se não me engano é assim que Submarino e outras lojas fazem.
Colocar separado como na primeira e na segunda assusta os clientes :p

**Comment by gopaulo** [comment]
Claudio,
  estou revisando o cálculo do juros e ele está errado - estamos somando apenas uma vez o juros e não o juros de parcelamento composto 

https://github.com/greguly/cielo-woocommerce/blob/master/includes/views/html-payment-form-webservice.php#l48

**Comment by gopaulo** [comment]
vou usar a fórmula de cálculo de prestações com juros - um link com a descrição da fórmula:
http://www.matematicadidatica.com.br/CalculoPrestacao.aspx

**Comment by claudiosmweb** [comment]
Otimo, ficou bom isso, entretanto estou vendo que estamos replicando o mesmo código em 3 lugares, vou tentar criar um método para isso, assim só damos manutenção em um lugar logo.

**Comment by claudiosmweb** [comment]
Acredito que falta apenas mostrar nesta tela.

![screenshot from 2015-03-29 19 34 32](https://cloud.githubusercontent.com/assets/1264099/6888131/aab12586-d64a-11e4-98de-54f7c754f071.png)

**Comment by claudiosmweb** [comment]
@gopaulo Ficou faltando apenas este issue agora.

Precisamos mudar essa mensagem, dizer com qual bandeira de cartão de crédito foi paga, em quantas parcelas e o total cobrado do cartão e etc.

Além de fazer isso com os e-mails (isso vamos criar templates, mas as frases serão as mesmas).

Também podemos aplicar isso para débito quando tem aquele desconto.

**Comment by claudiosmweb** [comment]
Acabei de ajeitar as coisas para isso, precisamos agora preencher os templates e mensagens e ai vai estar tudo pronto :)

**Comment by echogit** [comment]
Olá, parabéns pelo trabalho! O Método de Pagamento ficará em português? (Cartão de Crédito ou Credit Card como aparece na imgem?)

**Comment by claudiosmweb** [comment]
@echogit nem precisa fazer esse tipo de pergunta né? xD
Primeiro fazemos o plugin e depois traduzimos ;)

**Comment by claudiosmweb** [comment]
Além que esse Credit Card ai é o título do gateway que você pode mudar para qualquer outra coisa.

**Comment by gopaulo** [comment]
Eu vi que no template vc ta fazendo o call pro 'woocommerce_email_before_order_table' < vc acha melhor a gente mostrar só o texto dos parcelamentos ? pq o resto vai puxar do template do woocommerce mesmo né ..

**Comment by gopaulo** [comment]
Eu não sei se é algo espútido que eu estou fazendo mas o add_action não ta dando trigger pra mim nem no thankyou_page ou no view_order, woocommerce_email_after_order_table ... 

eu já vi alguns plugins que nao rodam o __construct direito mas não faz sentido pq ta rodando .. =/ #frustration

**Comment by claudiosmweb** [comment]
Então deve já rolar os templates que eu coloquei.
A ideia é dar feedback sobre o pagamento nos e-mails.
Tanto para debito quanto para crédito.
Por exemplo se você paga com PagSeguro, hora que o pagamento é aprovado, o cliente recebe e-mail do PagSeguro dizendo sobre isso.
Algumas pessoas não entendem direito que funcionou ok e o pedido esta processando e pago, por isso é legal avisar a forma de pagamento e confirmar que realmente foi pago e como.
Apenas para não sobrar nenhuma dúvida sobre o que aconteceu.

**Comment by gopaulo** [comment]
Não classe antiga do helper vc tinha alguns métodos estáticos né ? hoje se eu quiser acessar esses métodos eu preciso instanciar um gateway... 

Estou pensando em:

1) alterar get_installments_html() para aceitar além do parametro select e radio, aceitar html (gera só a string final já formatada) 

2) dentro de cielo-woocommerce adicionar o action
'''	add_action( 'woocommerce_order_items_table', array( $this, 'view_order_payment_details' ) );
'''
'''
	function view_order_payment_details($order) {
		$card_brand   = get_post_meta( $order->id, '_wc_cielo_card_brand', true );
		$card_brand   = WC_Cielo_Helper::get_payment_method_name( $card_brand );
		$installments = get_post_meta( $order->id, '_wc_cielo_installments', true );

		$installments_html = WC_Cielo_Helper:get_installments_html($order->get_order_total(),'html',$installments);

		$order->payment_method_title .= '<br/><small>'.$installments_html.'</small>';
	}
'''

O resultado seria algo parecida com a imagem .
![screen shot 2015-03-31 at 11 20 55 pm](https://cloud.githubusercontent.com/assets/3051206/6933366/aca0190c-d7fc-11e4-8414-4c37f920894c.png)

Mas pra isso eu precisaria desses métodos do helper (static ou acessá-los e alguma outra forma) 

não quero mexer muito no código antes de ouvir de vc

**Comment by claudiosmweb** [comment]
Removi os métodos estáticos por causa que não estavam sendo mais necessários, mas podemos voltar com eles.
Entretanto não acho que o action que você esta usando seja o certo, até porque no WooCommerce, acho que a partir do 2.2, nos mostrando já o método de pagamento assim.

Teria que usar o filtro `woocommerce_get_order_item_totals`, nele da para ver `payment_method` e assim adicionar esse texto a mais.

**Comment by claudiosmweb** [comment]
@gopaulo ficou assim:

![screenshot from 2015-04-05 21 27 31](https://cloud.githubusercontent.com/assets/1264099/6999282/a66587d4-dbda-11e4-9860-393a08cb9036.png)
![screenshot from 2015-04-05 21 27 38](https://cloud.githubusercontent.com/assets/1264099/6999283/a66aa8ae-dbda-11e4-9c2a-5f009c9ff77e.png)
